import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 侧边栏按 docs/ 的文件夹结构自动生成。
 * 各分组的中文名写在组目录的 _category_.json 里。
 * 新增版本时不用动这里：docs:version 会为快照目录生成对应的 versioned_sidebars。
 */
const sidebars: SidebarsConfig = {
  rmtSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
